
##### ===========================================================================================
##
##    MACRO FILE - OPTICAL EXAMPLE - ATLANTA IEEE 2017
##
##### ===========================================================================================


## =====================================================
## VISUALISATION & VERBOSE
## =====================================================

/vis/disable
# /control/execute mac/visu.mac
#/control/execute mac/verbose.mac
/vis/scene/endOfEventAction accumulate 100


## =====================================================
## GEOMETRY
## =====================================================

/gate/geometry/setMaterialDatabase GateMaterials.db

##
## World
##
/gate/world/geometry/setXLength 3 m
/gate/world/geometry/setYLength 3 m
/gate/world/geometry/setZLength 3 m
/gate/world/setMaterial Air



##
## Peak1
##
/gate/world/daughters/name              Peak1
/gate/world/daughters/insert            box
/gate/Peak1/placement/setTranslation           0.0 0.0 0.0 mm
/gate/Peak1/geometry/setXLength      10 mm
/gate/Peak1/geometry/setYLength      0.4 mm
/gate/Peak1/geometry/setZLength      0.2 mm
/gate/Peak1/setMaterial                        Silicon
/gate/Peak1/vis/forceWireframe
/gate/Peak1/vis/setVisible 1
/gate/Peak1/vis/setColor                       green

##
## Peak2
##
/gate/world/daughters/name              Peak2
/gate/world/daughters/insert            box
/gate/Peak2/placement/setTranslation           0.0 0.4 -0.05 mm
/gate/Peak2/geometry/setXLength      10 mm
/gate/Peak2/geometry/setYLength      0.4 mm
/gate/Peak2/geometry/setZLength      0.1 mm
/gate/Peak2/setMaterial                        Silicon
/gate/Peak2/vis/forceWireframe
/gate/Peak2/vis/setVisible 1
/gate/Peak2/vis/setColor                       cyan

##
## Sensor
##
/gate/world/daughters/name              Sensor
/gate/world/daughters/insert            box
/gate/Sensor/placement/setTranslation           0.0 0.4 0.2 mm
/gate/Sensor/geometry/setXLength      10 mm
/gate/Sensor/geometry/setYLength      10 mm
/gate/Sensor/geometry/setZLength      0.2 mm
/gate/Sensor/setMaterial                        Silicon
/gate/Sensor/vis/forceWireframe
/gate/Sensor/vis/setVisible 1
/gate/Sensor/vis/setColor                       red

/gate/Peak1/repeaters/insert linear
/gate/Peak1/linear/setRepeatNumber 12
/gate/Peak1/linear/setRepeatVector 0. 0.8 0. mm

/gate/Peak2/repeaters/insert linear
/gate/Peak2/linear/setRepeatNumber 12
/gate/Peak2/linear/setRepeatVector 0. 0.8 0. mm
## =====================================================
## PHYSICS
## =====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.1 mm
/gate/physics/Positron/SetCutInRegion   world 0.1 mm

# /gate/physics/Gamma/SetCutInRegion      phantomCyl 0.1 mm
# /gate/physics/Electron/SetCutInRegion   phantomCyl 0.1 mm
# /gate/physics/Positron/SetCutInRegion   phantomCyl 0.1 mm

/gate/physics/displayCuts


## =====================================================
## OUTPUT MANAGEMENT
## =====================================================

# /gate/phantomCyl/attachPhantomSD	

/gate/actor/addActor                               DoseActor  doseDistribution
# /gate/actor/doseDistribution/save                  outputAtPillar/output-gamma.mhd
/gate/actor/doseDistribution/save                  Gratingoutput-gamma.root
/gate/actor/doseDistribution/attachTo    	         Sensor
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               10 10 0.2 mm
/gate/actor/doseDistribution/setResolution         100 100 100
# /gate/actor/doseDistribution/setVoxelSize          0.1 0.1 0.1 mm

/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableUncertaintyDose true
/gate/actor/doseDistribution/enableNumberOfHits    true

# /gate/actor/addActor                     DoseActor  dose3d
# # /gate/actor/dose3d/save                  output/gamma-3d.mhd
# /gate/actor/dose3d/save outputAtPillar/Lana.root

# /gate/actor/dose3d/attachTo    	         phantomCyl
# /gate/actor/dose3d/stepHitType           random
# /gate/actor/dose3d/setPosition           0 0 0 cm
# # /gate/actor/dose3d/setSize               1 1 1 mm
# /gate/actor/dose3d/setResolution         2 2 2
# # /gate/actor/doseDistribution/setVoxelSize          0.1 0.1 0.1 mm
# /gate/actor/dose3d/enableEdep            true
# /gate/actor/dose3d/enableUncertaintyEdep true
# /gate/actor/dose3d/enableDose            true
# /gate/actor/dose3d/enableUncertaintyDose false
# /gate/actor/dose3d/enableNumberOfHits    false

# /gate/actor/addActor               SimulationStatisticActor stat
# /gate/actor/stat/save              outputAtPillar/stat-gamma.txt



## =====================================================
## INITIALISATION
## =====================================================

/gate/run/initialize

## =====================================================
## BEAMS
## =====================================================


/gate/source/addSource mybeam gps

/gate/source/mybeam/gps/particle gamma
#/gate/source/mybeam/gps/pos/type Beam
# /gate/source/mybeam/gps/pos/rot1 0 1 0
# /gate/source/mybeam/gps/pos/rot2 1 0 0
#/gate/source/mybeam/gps/pos/shape Circle
# /gate/source/mybeam/gps/pos/centre 0 100 0 cm
/gate/source/mybeam/gps/pos/centre 0 0 -100 cm
#/gate/source/mybeam/gps/pos/sigma_x 3 mm
# /gate/source/mybeam/gps/pos/sigma_y 3 mm

/gate/source/mybeam/gps/direction 0 0 1
/gate/source/mybeam/gps/ang/type iso
/gate/source/mybeam/gps/ang/mintheta 179.0 deg  #14 degree aperture
# /gate/source/mybeam/gps/ang/mintheta 89.5 deg  #14 degree aperture
# /gate/source/mybeam/gps/ang/maxtheta 90.5 deg  #14 degree aperture
# /gate/source/mybeam/gps/ang/minphi 89.5 deg  #14 degree aperture
# /gate/source/mybeam/gps/ang/maxphi 90.5 deg  #14 degree aperture
/gate/source/mybeam/gps/hist/point 0.25 0.004107824
/gate/source/mybeam/gps/hist/point 0.50 0.1295177
/gate/source/mybeam/gps/hist/point 0.75 0.4609022
/gate/source/mybeam/gps/hist/point 1.00 0.4609022   
/gate/source/mybeam/gps/hist/point 1.25 0.4435880   
/gate/source/mybeam/gps/hist/point 1.50 0.4084962   
/gate/source/mybeam/gps/hist/point 1.75 0.4084962   
/gate/source/mybeam/gps/hist/point 2.00 0.2496504   
/gate/source/mybeam/gps/hist/point 2.25 0.2367691  
/gate/source/mybeam/gps/hist/point 2.50 0.1867142   
/gate/source/mybeam/gps/hist/point 2.75 0.1382681   
/gate/source/mybeam/gps/hist/point 3.00 0.1304545   
/gate/source/mybeam/gps/hist/point 3.25 0.1484442   
/gate/source/mybeam/gps/hist/point 3.50 0.09496227   
/gate/source/mybeam/gps/hist/point 3.75 0.1246583   
/gate/source/mybeam/gps/hist/point 4.00 0.09773248   
/gate/source/mybeam/gps/hist/point 4.25 0.08891984   
/gate/source/mybeam/gps/hist/point 4.50 0.05154921   
/gate/source/mybeam/gps/hist/point 4.75 0.04184013   
/gate/source/mybeam/gps/hist/point 5.00 0.04803306   
/gate/source/mybeam/gps/hist/point 5.25 0.01624749   
/gate/source/mybeam/gps/hist/point 5.50 0.02715377   
/gate/source/mybeam/gps/hist/point 5.75 0.01199324   
/gate/source/mybeam/gps/hist/point 6.00 0.01573713 

#=====================================================
#  D A T A   O U T P U T   
#=====================================================
#/gate/output/root/enable
#/gate/output/root/setRootSinglesFlag 1
#/gate/output/root/setRootHitFlag 1
#/gate/output/root/setFileName output/grating.root

## =====================================================
## START BEAMS
## =====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 123456

/gate/application/noGlobalOutput
/gate/application/setTotalNumberOfPrimaries 100000000
/gate/application/start
	
