#/gate/source/mybeam/gps/ene/type   User
#/gate/source/mybeam/gps/hist/type  energy
#/gate/source/mybeam/gps/ene/diffspec 1

/gate/source/mybeam/gps/ene/type Arb
/gate/source/mybeam/gps/hist/type arb

/gate/source/mybeam/gps/hist/point 0.25 0.004107824
/gate/source/mybeam/gps/hist/point 0.50 0.1295177
/gate/source/mybeam/gps/hist/point 0.75 0.4609022
/gate/source/mybeam/gps/hist/point 1.00 0.4609022   
/gate/source/mybeam/gps/hist/point 1.25 0.4435880   
/gate/source/mybeam/gps/hist/point 1.50 0.4084962   
/gate/source/mybeam/gps/hist/point 1.75 0.4084962   
/gate/source/mybeam/gps/hist/point 2.00 0.2496504   
/gate/source/mybeam/gps/hist/point 2.25 0.2367691  
/gate/source/mybeam/gps/hist/point 2.50 0.1867142   
/gate/source/mybeam/gps/hist/point 2.75 0.1382681   
/gate/source/mybeam/gps/hist/point 3.00 0.1304545   
/gate/source/mybeam/gps/hist/point 3.25 0.1484442   
/gate/source/mybeam/gps/hist/point 3.50 0.09496227   
/gate/source/mybeam/gps/hist/point 3.75 0.1246583   
/gate/source/mybeam/gps/hist/point 4.00 0.09773248   
/gate/source/mybeam/gps/hist/point 4.25 0.08891984   
/gate/source/mybeam/gps/hist/point 4.50 0.05154921   
/gate/source/mybeam/gps/hist/point 4.75 0.04184013   
/gate/source/mybeam/gps/hist/point 5.00 0.04803306   
/gate/source/mybeam/gps/hist/point 5.25 0.01624749   
/gate/source/mybeam/gps/hist/point 5.50 0.02715377   
/gate/source/mybeam/gps/hist/point 5.75 0.01199324   
/gate/source/mybeam/gps/hist/point 6.00 0.01573713 