
## =====================================================
## OUTPUT MANAGEMENT
## =====================================================

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  GratingOutput.root
/gate/actor/doseDistribution/attachTo    	       SensorEpi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               12 17.04 0.010 mm
/gate/actor/doseDistribution/setResolution         200 284 10 #for 60 micron pixel x4

/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false
/gate/actor/doseDistribution/enableNumberOfHits    true


## =====================================================
## OUTPUT MANAGEMENT
## =====================================================

# /gate/actor/addActor                               DoseActor  doseBulk
# /gate/actor/doseBulk/save                  Test10x10Bulk.root
# /gate/actor/doseBulk/attachTo    	       Bulk
# /gate/actor/doseBulk/stepHitType           random
# /gate/actor/doseBulk/setPosition           0 0 0 cm
# /gate/actor/doseBulk/setSize               12 17.04 0.390 mm
# /gate/actor/doseBulk/setResolution         20 284 10 #for 60 micron pixel x4

# /gate/actor/doseBulk/enableEdep            true
# /gate/actor/doseBulk/enableUncertaintyEdep true
# /gate/actor/doseBulk/enableDose            false
# /gate/actor/doseBulk/enableUncertaintyDose false
# /gate/actor/doseBulk/enableNumberOfHits    true

## =====================================================
## OUTPUT MANAGEMENT
## =====================================================

# /gate/actor/addActor                        DoseActor  dosePeaks
# /gate/actor/dosePeaks/save                  Test10x10.root
# /gate/actor/dosePeaks/attachTo    	        Peak1
# /gate/actor/dosePeaks/attachTo    	        Peak2
# /gate/actor/dosePeaks/stepHitType           random
# /gate/actor/dosePeaks/setPosition           0 0 0 cm
# /gate/actor/dosePeaks/setSize               12 17.04 0.300 mm
# /gate/actor/dosePeaks/setResolution         20 284 10 #for 60 micron pixel x4

# /gate/actor/dosePeaks/enableEdep            true
# /gate/actor/dosePeaks/enableUncertaintyEdep true
# /gate/actor/dosePeaks/enableDose            false
# /gate/actor/dosePeaks/enableUncertaintyDose false
# /gate/actor/dosePeaks/enableNumberOfHits    true
