## =====================================================
## PHYSICS
## =====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.1 mm
/gate/physics/Positron/SetCutInRegion   world 0.1 mm

/gate/physics/Gamma/SetCutInRegion      Absorber 0.0001 mm
/gate/physics/Electron/SetCutInRegion   Absorber 0.0001 mm
/gate/physics/Positron/SetCutInRegion   Absorber 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      Pb-box 0.0002 mm
/gate/physics/Electron/SetCutInRegion   Pb-box 0.0002 mm
/gate/physics/Positron/SetCutInRegion   Pb-box 0.0002 mm

/gate/physics/displayCuts
