## =====================================================
## PHYSICS
## =====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.1 mm
/gate/physics/Positron/SetCutInRegion   world 0.1 mm

/gate/physics/Gamma/SetCutInRegion      PSA 0.0001 mm
/gate/physics/Electron/SetCutInRegion   PSA 0.0001 mm
/gate/physics/Positron/SetCutInRegion   PSA 0.0001 mm

/gate/physics/displayCuts
