 ##### ===========================================================================================
##
##    MACRO FILE - OPTICAL EXAMPLE - ATLANTA IEEE 2017
##
##### ===========================================================================================


## =====================================================
## VISUALISATION & VERBOSE
## =====================================================

/vis/disable
# /control/execute mac/visu.mac
# /control/execute mac/verbose.mac
# /vis/scene/endOfEventAction accumulate 100
# /vis/viewer/set/viewpointThetaPhi 90 0
## =====================================================
## GEOMETRY
## =====================================================

/gate/geometry/setMaterialDatabase GateMaterials.db

##
## World
##
/gate/world/geometry/setXLength 3 m
/gate/world/geometry/setYLength 3 m
/gate/world/geometry/setZLength 3 m
/gate/world/setMaterial Vacuum

/control/execute HeadGeometry.mac
/control/execute SensorGeometry.mac












## =====================================================
## OUTPUT MANAGEMENT
## =====================================================

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  Gratingoutput-gamma.root
/gate/actor/doseDistribution/attachTo    	       Sensor
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               12 12 0.01 mm
/gate/actor/doseDistribution/setResolution         200 200 1 #for 60 micron pixel x4
# /gate/actor/doseDistribution/setVoxelSize          0.1 0.1 0.1 mm

/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
# /gate/actor/doseDistribution/enableDose            true
# /gate/actor/doseDistribution/enableUncertaintyDose true
/gate/actor/doseDistribution/enableNumberOfHits    true

# /gate/actor/addActor               SimulationStatisticActor stat
# /gate/actor/stat/save              outputAtPillar/stat-gamma.txt

## =====================================================
## INITIALISATION
## =====================================================

/gate/run/initialize

## =====================================================
## BEAMS
## =====================================================

/gate/source/addSource mybeam gps

/gate/source/mybeam/gps/particle gamma
# /gate/source/mybeam/gps/pos/rot1 0 1 0
# /gate/source/mybeam/gps/pos/rot2 1 0 0
# /gate/source/mybeam/gps/pos/centre 0 100 0 cm
/gate/source/mybeam/gps/pos/centre 0 0 -100 cm
/gate/source/mybeam/gps/direction 0 0 1
/gate/source/mybeam/gps/ang/type iso
/gate/source/mybeam/gps/ang/mintheta 176 deg  #55 degree aperture
# /gate/source/mybeam/gps/ang/mintheta 89.5 deg  #14 degree aperture
# /gate/source/mybeam/gps/ang/maxtheta 90.5 deg  #14 degree aperture
# /gate/source/mybeam/gps/ang/minphi 89.5 deg  #14 degree aperture
# /gate/source/mybeam/gps/ang/maxphi 90.5 deg  #14 degree aperture
/gate/source/mybeam/gps/hist/point 0.25 0.004107824
/gate/source/mybeam/gps/hist/point 0.50 0.1295177
/gate/source/mybeam/gps/hist/point 0.75 0.4609022
/gate/source/mybeam/gps/hist/point 1.00 0.4609022   
/gate/source/mybeam/gps/hist/point 1.25 0.4435880   
/gate/source/mybeam/gps/hist/point 1.50 0.4084962   
/gate/source/mybeam/gps/hist/point 1.75 0.4084962   
/gate/source/mybeam/gps/hist/point 2.00 0.2496504   
/gate/source/mybeam/gps/hist/point 2.25 0.2367691  
/gate/source/mybeam/gps/hist/point 2.50 0.1867142   
/gate/source/mybeam/gps/hist/point 2.75 0.1382681   
/gate/source/mybeam/gps/hist/point 3.00 0.1304545   
/gate/source/mybeam/gps/hist/point 3.25 0.1484442   
/gate/source/mybeam/gps/hist/point 3.50 0.09496227   
/gate/source/mybeam/gps/hist/point 3.75 0.1246583   
/gate/source/mybeam/gps/hist/point 4.00 0.09773248   
/gate/source/mybeam/gps/hist/point 4.25 0.08891984   
/gate/source/mybeam/gps/hist/point 4.50 0.05154921   
/gate/source/mybeam/gps/hist/point 4.75 0.04184013   
/gate/source/mybeam/gps/hist/point 5.00 0.04803306   
/gate/source/mybeam/gps/hist/point 5.25 0.01624749   
/gate/source/mybeam/gps/hist/point 5.50 0.02715377   
/gate/source/mybeam/gps/hist/point 5.75 0.01199324   
/gate/source/mybeam/gps/hist/point 6.00 0.01573713 

## =====================================================
## START BEAMS
## =====================================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 123456

/gate/application/noGlobalOutput
/gate/application/setTotalNumberOfPrimaries 1282538368
/gate/application/start
	
